server:
  port: 3253
spring:
  application:
    name: project
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      maxFileSize: 4096MB
      maxRequestSize: 4096MB

# 统一开关配置
enable:
  login: false # 是否需要登录才能访问接口
  scheduling: false # 是否启动定时任务
  minio: false # 是否启动minio
